### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by sabas1080** [Seeed-Studio/Wio_Link#1]
Hi

will have schematic of wio link?

Thanks

**Comment by KillingJacky** [comment]
Yes, we will open source the schematic when the ks campaign finish.

**Comment by hallard** [comment]
thanks, would be interesting. Does the analog is the ESP8266 one or have another external chip used ?

**Comment by sabas1080** [comment]
The open hardware can not condition the crowfounding

**Comment by KillingJacky** [comment]
@hallard Yes, the analog is ESP8266's builtin.

**Comment by KillingJacky** [comment]
@sabas1080 Yes, it's conditioned by the stability of the hardware design. We are still tuning the design to ensure that we ship the stable design to ks backers.

**Comment by sabas1080** [comment]
Thanks
