### ISSUE TITLE
unable to connect wio board to docker P1

### ISSUE THREAD

**Issue by Koen76** [Seeed-Studio/Wio_Link#13]
When I try to configure the wio board using my phone it doesn't work. 
I see the following in the apache access log of the reverse proxy:
94.208.95.110 - - [14/Apr/2016:20:54:10 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"
94.208.95.110 - - [14/Apr/2016:20:54:10 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"
94.208.95.110 - - [14/Apr/2016:20:54:10 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"
94.208.95.110 - - [14/Apr/2016:20:54:10 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"
94.208.95.110 - - [14/Apr/2016:20:54:10 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"
94.208.95.110 - - [14/Apr/2016:20:54:13 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"
94.208.95.110 - - [14/Apr/2016:20:54:17 +0200] "GET /v1/nodes/list?access_token=hmT2QQP55KvbG-4RJlu4zrt4fd13OQDtAXtAyoqOKWA HTTP/1.1" 304 - "-" "Wio Link/1.3 (iPhone; iOS 9.3.1; Scale/2.00)"

what can be the issue?

**Comment by awong1900** [comment]
Hi Koen76,
This issue is the iphone is look for just configured Wio Link.
This server is your private server?  

Any more detail info? or steps?
