### ISSUE TITLE
Build dependencies not documented

### ISSUE THREAD

**Issue by 9037568** [Seeed-Studio/Wio_Link#15]
Build dependencies are not documented, but should be.

For example, I was encountering the following error when attempting to compile the project:

> X:\projects>build_firmware.py
> Traceback (most recent call last):
>   File "X:\projects\build_firmware.py", line 27, in <module>
>     import yaml
> ImportError: No module named yaml

And when I tried to install yaml, I got this error:

> X:\projects>pip install yaml
> Collecting yaml
>   Could not find a version that satisfies the requirement yaml (from versions: )
> No matching distribution found for yaml

**Comment by KillingJacky** [comment]
Hi, is this what you concerned? https://github.com/Seeed-Studio/Wio_Link/wiki/Server-Deployment-Guide#22-python-modules-required  Did you deploy your private server with docker?

**Comment by 9037568** [comment]
Well, that explains why I didn't find that information. I'm not deploying to a private server, just trying to compile the project. Thanks for the pointer.
