### ISSUE TITLE
Update firmware

### ISSUE THREAD

**Issue by zylopezr** [Seeed-Studio/Wio_Link#17]
Hello,  I've worked with a conventional esp8266, but I've bougth your target and I'd like to update a firmware from my computer, could you tell me how to connect the pins?  (I have a usb-ttl convertor and mi SO is Linux - ubuntu)

**Comment by KillingJacky** [comment]
Hi, please download the schematic of wio link here http://www.seeedstudio.com/wiki/File:Wio_Link_SCH_v1.0.rar  (updated link, thanks to @moxondesign). Then you can refer to the wire connection of wio link to connect your esp8266 board together.

**Comment by zylopezr** [comment]
Hello, me again. 
I've been trying to update the firmware using Ubuntu, I'm following this tutorial,  https://learn.adafruit.com/downloads/pdf/building-and-running-micropython-on-the-esp8266.pdf
I have to connect the board to usb-ttl convertor, but I've not found the correct way, Advanced User Guide says one have to connect UART1 TX to the pin RX of convertor and also the Ground line, I did it but I got an error "Inappropriate ioctl for device" like if the board is not well connected. Do you have any information about updating firmware using Ubuntu, or about this error?
Thank u so much.

**Comment by moxondesign** [comment]
Hi, That link is broken, where is the schematic please?

**Comment by moxondesign** [comment]
found it here - http://www.seeedstudio.com/wiki/File:Wio_Link_SCH_v1.0.rar

**Comment by KillingJacky** [comment]
thank you!
