### ISSUE TITLE
Rename the project from Wio_Link to Wio

### ISSUE THREAD

**Issue by yexiaobo-seeedstudio** [Seeed-Studio/Wio_Link#20]
There are new product called [Wio Node](http://www.seeedstudio.com/depot/Wio-Node-p-2637.html?utm_source=https://github.com/Seeed-Studio/Wio_Link) has been released.

I think we should rename the project from Wio_Link to Wio.

**Comment by KillingJacky** [comment]
Think it's ok. BTW, changing url will bring many problems.
