### ISSUE TITLE
Advanced use: unclear instructions

### ISSUE THREAD

**Issue by YPares** [Seeed-Studio/Wio_Link#21]
In https://github.com/Seeed-Studio/Wio_Link/wiki/Advanced%20User%20Guide
the instruction as to how "Use Wio Link's SDK and Program in Arduino-Style" are really not clear.

Files `Main.cpp` and `connection_config.json` for instance are mentioned but don't exist in the git repository. Also the possibility to use the Dockerfile to get ESP SDK isn't mentioned.

An example showing for instance how to read the DHT and display the values on the RGB LCD could be very useful here.

**Comment by KillingJacky** [comment]
Hi YPares,

Thanks for your pointer. We're updating the documentations.

**Comment by KillingJacky** [comment]
Doc updated.
