### ISSUE TITLE
COM FAIL (serial port open error)

### ISSUE THREAD

**Issue by jaimeaxt** [Seeed-Studio/Wio_Link#22]
Hi guys! I am having some troubles here.
- I downloaded the app (for Android) and I created my account
- I connected my phone to my WIFI network and I enabled the GPS
- I connected the WIO Link to the power and press the config button (for 4 seconds) 
- I press the "GOT READY" button and I can see the WIFI of the WIO LINK (WioLink_XXXXXX)
- Whe I press WioLink_XXXXXX, the phone loss the WIFI connection and the app show "Connecting to WioLink_XXXXXX"... and I am still waiting...

My phone is an Android 5.0.1 (Galaxy S4)

I thought that WIO LINK was bricked, so I tried to follow the procedure indicated in the Advanced User Guide, but I receive another message: COM FAIL (serial port open error)

![captura2](https://cloud.githubusercontent.com/assets/6740861/15182795/9ebc16a8-1764-11e6-9fcf-26f960b16d80.PNG)

Please help!!!

**Comment by awong1900** [comment]
@jaime-axt 1. Ensure COM PORT is right.  See 
![image](https://cloud.githubusercontent.com/assets/4022612/14639934/af559b78-0671-11e6-9238-76b3a79ae1df.png)
2.  If the app stuck in "Connecting to WioLink_XXXXXX"... ,  try to manually connect to WioLink_xxx on the system WI-FI settings.  This help app enter next step.  
This error does not happen often, if I can send the app log by email, which will help better location.

**Comment by jaimeaxt** [comment]
I configured manually the wifi to connect to WioLink, and now works perfect.

Thank you very much!
