### ISSUE TITLE
Solid blue light

### ISSUE THREAD

**Issue by tube0013** [Seeed-Studio/Wio_Link#24]
I reconfigured my wio link to connect to a new wifi network.  It was working.  In plugged it and moved it to a new location.  It boots but the blue led stays lit.

I've tried reconfiguring it by holding the button but it never chances mode.  I plugged into my computer and ran the wio Python program, it sees it but when I try to push network config to the device it just spins.

Is this unit now dead/bricked?  Any options besides trying to reflash based in the advanced instructions?

Thabks

**Comment by KillingJacky** [comment]
Hi, it should always respond the "CONFIG" button. If the Wio firmly can't go into configuration mode, we can say it's bricked.
