### ISSUE TITLE
Undocumented blue LED flashes

### ISSUE THREAD

**Issue by tube0013** [Seeed-Studio/Wio_Link#25]
My Wio Link fell offline today.  When I got home and looked at the board the blue LED was staying lit for approximately 8-10 seconds (my count) then flashing quickly then repeating this cycle.  Board is unresponsive to config button push and hold, and power cycling the board brings it back to the same state.

**Comment by tube0013** [comment]
I isolated this issue, it only occurs when I have my Air Quality Groove plugged into the Analog port on the Wio Link board.  If I remove the sensor, the board behaves normally.  is this a bad sensor or something?  is this expected behavior?

**Comment by awong1900** [comment]
@tube0013 There is no problem on our side.  If you press reset button or replug the power. Is board change to normal?
