### ISSUE TITLE
Wio Link does not work with many WiFi setups

### ISSUE THREAD

**Issue by JackStouffer** [Seeed-Studio/Wio_Link#26]
Wio Link does not connect to a WiFi network if:
- The network has a terms of service web page pop up that appears after you connect
- The network uses enterprise WiFi setup with a username and password

**Comment by KillingJacky** [comment]
Hi Jack, it's hard for a wifi soc to handle web page pop up or enterprise wifi setup. We'll keep eye on the solutions about this issue, if you've found someone done this, please point to us

**Comment by KillingJacky** [comment]
As this is a long term improvement, we mark your suggestion down, and close this issue for now.
