### ISSUE TITLE
no such table

### ISSUE THREAD

**Issue by Koen76** [Seeed-Studio/Wio_Link#3]
I've downloaded the docker for hosting my own api server. When I try to create a user suing my phone or the Pyhton scripts I receive the same error: "no such table: users"

Can you please advise?

**Comment by KillingJacky** [comment]
Hi, the repo wasn't uploaded completely. the database file was absent purposely. Now the database file is here. Please repull the docker image after a few minutes when the image building is done at docker hub.

**Comment by Koen76** [comment]
Jack, I have tested and it is working again. Thanks, koen

**Comment by KillingJacky** [comment]
Good to hear, you're wel, koen
