### ISSUE TITLE
scan_drivers python script fails when start directory contains .git directory

### ISSUE THREAD

**Issue by 9037568** [Seeed-Studio/Wio_Link#31]
When I run scan_drivers.py after cloning the repository, this error occurs:

```
=========
[]

ERR: can not find class file of X:\projects\electronics\wiolink\github\Wio_Link\grove_drivers\.git
```

The program should ignore directories such as this.

**Comment by airdissy** [comment]
Hi,
Did you also clone the grove drivers directory, 
`git submodule init`
`git submodule update`

I'm not export, but I refer to below pages:
http://www.seeed.cc/project_detail.html?id=1273&utm_source=allwio&utm_medium=mailchimp&utm_campaign=Molly0628

**Comment by 9037568** [comment]
Yes, I cloned the drivers directory. But I did it separately using "git clone".

**Comment by KillingJacky** [comment]
@9037568 Yes, that's a bug. Thank you!

**Comment by KillingJacky** [comment]
Hotfixed, will close this :)
