### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by samhotchkiss** [Seeed-Studio/Wio_Link#39]
I have an issue that started a few weeks ago, where I simply cannot connect to the Wio servers through any WiFi network nor can I set debug on the device.

I've tried:
• Connecting to multiple networks, once I enter the credentials for the new network, the light just blinks in the "connecting to server" pattern for 10+ minutes.  I can see it connected to my WiFi, but it never finishes setting up

• Flashing the firmware.  Same results

• Turning on debug on the device.  I put it into configure mode, connect to its wifi, then:

```
wio config --debug on
Setting failure!!
Note:
    1. Ensure your device is Configure Mode.
    2. Change your computer network to Wio's AP.
```

Any ideas?  It worked perfectly for months and was being used on a daily basis before this happened

**Comment by KillingJacky** [comment]
Hi @samhotchkiss Have you switched your device registration to the new server? Like we mentioned here (also we sent mails) http://www.seeedstudio.com/blog/2016/08/25/attention-wio-old-server-shut-down/?utm_source=mailchimp&utm_medium=edm&utm_campaign=wio_0825
