### ISSUE TITLE
Failing to configure

### ISSUE THREAD

**Issue by lawrie** [Seeed-Studio/Wio_Link#4]
Hi, I am having difficulty configuring my Wio links. After many tries one of them is now configured, but I have tried 20 or 30 times and the other one will not configure. I always get the message saying Wio Link cannot connect to the router. I am providing the correct password. 

The Wio Link stays in "breathing mode". There is no other activity on the LEDs, so it looks like it is not getting the configuration message.

I have tried connecting a console to the Wio link UART and seeing if there are any diagnostics. I see the start-up diagnostic messages. In config mode the baud rate is 115200. I then see no other messages Is there any way of getting and diagnostic information to see what is going wrong?

My phone is an Android Moto G running Android 6.0.

**Comment by KillingJacky** [comment]
Hi Lawrie

Sorry for the inconvenience. From the description, I agree with you that the Wio Link doesn’t even recv the config message. I’m sending you a firmware with debugging message enabled, please re-flash the firmware with the guide here: https://github.com/Seeed-Studio/Wio_Link/wiki/Advanced%20User%20Guide#5-repair-bricked-wio-link https://github.com/Seeed-Studio/Wio_Link/wiki/Advanced%20User%20Guide#5-repair-bricked-wio-link the only diff is to use user1.bin & user2.bin in my email attachment. (Or if your pc is linux or mac, you can use esptool as showed in the attached archive.

When you re-flashed the firmware, see what happened in the UART console ( baud rate is 74880 ). Also you can try to join the SSID of WioLInk with your PC and then try to ping Wio Link, see what happened. If all this failed, please send me piece of debugging messages, and you could fall into the last hope - use the cli tool to setup wio link. 

The cli tool is here https://github.com/Seeed-Studio/wio-cli https://github.com/Seeed-Studio/wio-cli, it uses usb cable to config wio link

Hope this will help and look forward to your feedback. 

Best,
Jack

---

Seeed Technology Co., Ltd
Software Team

[Uploading firmware_of_wiolink.zip…]()

**Comment by KillingJacky** [comment]
The upload to github aborts all the time. I put the archive here: http://www.seeedstudio.com/wiki/images/9/92/Firmware_of_wiolink.zip

**Comment by lawrie** [comment]
Hi Jack,

I flashed the new firmware.

The instructions in the advanced User Guide are confusing. It says:

a.. Press and hold FUNCTION key, then press RESET key, then release both 

I had to press and hold the reset button, and then the config button and then release both.

I can see I have the new firmware as I do not get the breathing blue LED when I go in to config mode.

I have attached images of the diagnostics I get with baud rate 74880 and 115200. As I said before, the baud rate seems to change to 115200 in config node. I saw a Serial.begin(115200) in the network.cpp code for that path, but was confused about the use of Serial and Serial1 for diagnostics.

At both baud rates, I see nothing when I send the config message from my phone.

Does it make a difference whether I use the USB port for diagnostics, or attach a CP210x device to the TX line on the UART Grove port?  I seem to get the same diagnostics from both.

I will try the cli tool.

Lawrie

**Comment by lawrie** [comment]
Hi Jack,

I successfully used the wio cli tool to setup the device.

Thanks,

Lawrie

**Comment by KillingJacky** [comment]
Hi Lawrie,

The debugging console is UART1, We only expose the TX of UART1 at GPIO2, which is right there beside GPIO13. The release version firmware uses GPIO2 to drive LED, while the debug version uses GPIO2 as UART1 TX.

**Comment by lawrie** [comment]
Hi Jack,

But how do I connect to GPIO2? Which pin on which connector is it exposed as? 

Is there a schematic for the board?

Lawrie

**Comment by KillingJacky** [comment]
the silk screen on the board indicates the corresponding GPIO.
![qq20160401-0](https://cloud.githubusercontent.com/assets/5130185/14202428/7699a6e4-f82a-11e5-9c17-17d944e44f15.png)

**Comment by lawrie** [comment]
Hi Jack,

Thanks for that. I should have realized that they were GPIO numbers.

Here is the diagnostics I get on UART1:

Boot reason: SOFT_RESTART
Node name: esp8266_node
FW version: 1.1
Chip id: 0x008b793b
Free heap size: 25816
Private key: ebd5be8f3451ab74bc070ca25d109e3d
Node SN: 72d0d095dcdd2c357368f07af0aa690a
Data server: 45.79.4.239
OTA server: 45.79.4.239
OTA result flag: 255
enter AP mode ... 
SSID: WioLink_8B793B

---

This confirms that the config message is not being received.

I don’t have a problem any more as I setup the device with wio cli.

Lawrie

**Comment by awong1900** [comment]
Hi Iawrie,

Still can't configure wiolink with android app? 
I will check this issue with same phone device. 

Ten

**Comment by lawrie** [comment]
Hi Ten,

Yes, that’s right.

Out of 50 or more attempts it has only worked once.

It is a Moto G running Android 6.0.

I will try another phone on my network, when I get a chance.

Lawrie

**Comment by awong1900** [comment]
Hi lawrie,

I can't find Moto G with Android 6.0, But I test Moto G with Android 5.0 and Nexus 6 with 6.0, be configure success.  
Please check the version of your app is v2.1.2 ? 

Ten

**Comment by lawrie** [comment]
Yes, it is v2.1.2.

Lawrie

**Comment by retro486** [comment]
I was having this same issue but I figured out a bit of a workaround that worked on two boards for me: http://blog.rdkl.us/setting-up-the-wio-link/

Basically, make sure you have the correct USB drivers installed for your system, use the wio-cli toolkit, don't wait for the wio to become available, manually enter your wifi details, reset and 4 second config WHILE wio-cli is trying to send the new config to your wio link. Usually after releasing the config button during this step the config goes right in and moves on to testing then you can use the app to configure it as per usual.

**Comment by KillingJacky** [comment]
Thanks for your info, Russ.
Hello Lawrie, how is it going there? Have you solved the problem?
