### ISSUE TITLE
Moto G 4 Plus WiFi permission

### ISSUE THREAD

**Issue by sabas1080** [Seeed-Studio/Wio_Link#44]
Hi 

I have Moto G 4 Plus and the app always asks me to check the wifi permissions, although the permissions granted appear

If you can pass that application window, try to connect with the link I get error 1042

Android version 6.01

Thanks

**Comment by sabas1080** [comment]
I have done the GPS mentioned in #41, but I still have the error 1042

**Comment by sabas1080** [comment]
I am testing with another device and get error 1044

It looks like the wio link can not connect to the server

**Comment by awong1900** [comment]
@sabas1080 Can you tell me the blue led status when the phone display 1044? If the led is blink once per second, means the device is online. If it blink twice quickly, means can't get ip address, you can check your router's password.

**Comment by sabas1080** [comment]
with error 1042, the led blnk very low, in mode setup

**Comment by awong1900** [comment]
Than means the device did not receive the information from APP.  Make sure your phone had connect to Wio's device hot spots, f the automatic connection fails, please connect manually. Then click the Wio's SSID on the step.

**Comment by KillingJacky** [comment]
Will close this, feel free to reopen it if any further question.
