### ISSUE TITLE
Web interface for Wio_link Private server

### ISSUE THREAD

**Issue by kp372** [Seeed-Studio/Wio_Link#48]
I don't think it as an issue but I tried to look around but I could find any answer. So I am posting it here. 

Does Wio Link Server have some kind of web interface to moderate user and devices? If yes,  it will be great if you can point me out some resource for that.

**Comment by awong1900** [comment]
Sorry there is no such web page. You can use the [CLI tool](https://github.com/Seeed-Studio/wio-cli) on the PC to easily display all device lists. 
![image](https://cloud.githubusercontent.com/assets/4022612/26707604/909252e6-4778-11e7-8a86-f9b942fb6417.png)

**Comment by KillingJacky** [comment]
Will close this, feel free to reopen it if any further question.
