### ISSUE TITLE
Read  125KHz RFID Reader

### ISSUE THREAD

**Issue by dynamik1703** [Seeed-Studio/Wio_Link#49]
Hey guys,

it's a lot of fun to build projects with the Wio.

I'm wondering how it is possible to read a card ID with a RFID Reader connected to a Wio?

Thanks.

**Comment by awong1900** [comment]
Thank you for your support.  I think you need add driver for this.

**Comment by dynamik1703** [comment]
Hey awong1900, do you have a link to a similar project?

**Comment by awong1900** [comment]
Here https://github.com/Seeed-Studio/PN532

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
