### ISSUE TITLE
Deploy a Local Lean Data Exchange Server into Raspberry Pi

### ISSUE THREAD

**Issue by NalinSilva** [Seeed-Studio/Wio_Link#51]
Hello everyone,
I am new to this environment and sorry for any inconvenience. I am trying to deploy a lean server into Rpi and still could not do that. When start the lean_server it show the message on cmd as follows.
Please help me to solve this issue
![lean_server](https://user-images.githubusercontent.com/30592895/28774695-4c08c80e-760c-11e7-8b9d-8544aa32d336.PNG)

**Comment by KillingJacky** [comment]
You should use python 2.

**Comment by NalinSilva** [comment]
Thanks for quick response. I'll try with python 2 Thanks

**Comment by NalinSilva** [comment]
is it ok with python2.7.
when i run 'pip install pycrypto'  terminate the instalation process and show
![lean_server2](https://user-images.githubusercontent.com/30592895/28776626-01ab282a-7615-11e7-9bc3-13178bde8610.PNG)

**Comment by NalinSilva** [comment]
hello Sir,
 pycrypto installed successfully after installing python-dev. Now "concurrent : 344" error msg is missing with python 2.I'am trying  to connect Wio app with lean server now.I'll give update asap when done it.
Thanks for you supporting.

**Comment by NalinSilva** [comment]
Hi,Sorry for the late, I had to move on another task immediately.Now i got following msg on Rpi
![lean_server3](https://user-images.githubusercontent.com/30592895/28954219-47935770-78fb-11e7-80b5-a7e9c957924c.PNG)

but still i could not connect node via lean server using wio app.when i try i got response as undefined in wio app

**Comment by NalinSilva** [comment]
Done now i can connect lean server using wio app.when i give the data excahange server IP with '' http://''  i got the data of sensor which is connected to the wio node.Anyware thanks for help to Mr. KillingJacky.
