### ISSUE TITLE
Help setting up the Wio Tracker

### ISSUE THREAD

**Issue by KamalBudhabhatti** [Seeed-Studio/Wio_Link#52]
Sir,
I am based in Africa and I purchase Wiotracker board. I am totally new to IOT and Arduino I am not able to move forward.

1) When I terminal the board, I get following Error.
Vgnss=7.59    vgnss error
io_value=3      IO test fail
VBAT=7.92    Vbat error
V3V3B=7.43

2) Which board type I must select when I am on Arduino IDE ?

3) When I upload the files in the IDE, I get error avrdude: butterfly_recv(): programmer is not responding

Some experts please help me.

**Comment by KillingJacky** [comment]
Hi, 
Please refer to this wiki page: http://wiki.seeed.cc/wio_gps_board/

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
