### ISSUE TITLE
Lean server can not start with private OTA where run in local machine

### ISSUE THREAD

**Issue by NalinSilva** [Seeed-Studio/Wio_Link#53]
Hello All,
another issue trying to stop me. When i am trying to run lean server in online mode in Rpi  it's give error message as follow. OTA is running in another PC. 
![lean_server4](https://user-images.githubusercontent.com/30592895/29120624-be354cd6-7d28-11e7-8337-f04032af6fe9.PNG)

Please help me to solve this one too.Thank you

**Comment by KillingJacky** [comment]
Sorry for delay, do you still have this issue? it seems to be a firewall issue or port issue.

**Comment by NalinSilva** [comment]
yes sir, Thank you for your reply never mind delay. I will try and give
feedback soon thank you again.
