### ISSUE TITLE
error: time out in notifying the node 

### ISSUE THREAD

**Issue by yanndouze** [Seeed-Studio/Wio_Link#6]
Hello

I have this error message when I try to update the node (OTA) : 

> error: time out in notifying the node 

What can I do ?

Best Regards
Yann

**Comment by KillingJacky** [comment]
Hi Yann,

**Comment by KillingJacky** [comment]
Hi Yann,

This error is basically caused by network latency. Are your Wio Link connecting SEEED's server? Which server are they connecting(international or china)? Which country are you in?

**Comment by yanndouze** [comment]
Hi Jack

I'm living in France so I don't really know which server is used ?
Where can I check this information ?
I just take a look at the Wio App and It seems to be the international
server... (http://iot.seeed.cc )

Yann

**Comment by awong1900** [comment]
Hi yanndouze,

You can use international sever.

**Comment by vali77** [comment]
Hi Yann, i had the same problem today, fix it by moving closer to my router in my case is was a wifi range issue.

**Comment by yanndouze** [comment]
Hello

I'm just behind my router and I'm using the international server (Main
server : https://iot.seeed.cc (international) )
What can I do more because I have all the time the same error  ?
Thanks for your help
Best Regards
Yann

2016-04-03 22:36 GMT+02:00 vali77 notifications@github.com:

> Hi Yann, i had the same problem today, fix it by moving closer to my
> router in my case is was a wifi range issue.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Seeed-Studio/Wio_Link/issues/6#issuecomment-205050523

## 

---

Yann DOUZE

## Mob : +33 6 61 11 48 89

**Comment by awong1900** [comment]
@yanndouze Can you give me your account? Then i can do more test. 
If can, send it to teng.wang@seeed.cc, include your password and ensure the wiolink is online.

**Comment by KillingJacky** [comment]
Close, if further more problems, please reopen.
