### ISSUE TITLE
Cannot download the bootloader binary

### ISSUE THREAD

**Issue by matsujirushi** [Seeed-Studio/Wio_Link#63]
I cannot download the bootloader binary in [this page](https://github.com/Seeed-Studio/Wio_Link/wiki/Advanced%20User%20Guide).
Please check.
![image](https://user-images.githubusercontent.com/8079404/61358365-22ecc500-a8b5-11e9-939c-1a81e63b36ee.png)

**Comment by KillingJacky** [comment]
Hi @matsujirushi Thanks for reporting, get fixed.
